using System;
using System.Collections.Generic;
using System.Text;

namespace projEuler.Problems
{

    /*
     Even Fibonacci numbers
    Problem 2

    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

     */

    public class Problem0002 : ProblemBase
    {

        IEnumerable<int> GetFiboNumbers(int s0, int s1)
        {
            yield return s0;
            yield return s1;

            var v = s0 + s1;

            while(v < 4_000_000)
            {
                yield return v;
                s0 = s1;
                s1 = v;
                v = s0 + s1;
            }
            

        }

        private int GetSumAproach1()
        {
            var fiboN = GetFiboNumbers(1, 2);

            var total = 0;
            int i = 0;
            foreach (var n in fiboN)
            {
                i++;
                if (n % 2 == 0)
                    total += n;
                    
            }
            //Console.WriteLine($"{i} items");
            return total;
        }

        private int GetSumAproach2()
        {
            

            var queue = new Queue<int>();
            queue.Enqueue(1);
            queue.Enqueue(2);

            var total = 0;
           
            int s0;
            int s1;
            do
            {
                s0 = queue.Dequeue();
                s1 = queue.Dequeue();
                if (s0 % 2 == 0)
                    total += s0;
                var curr = s0 + s1;
                queue.Enqueue(s1);
                queue.Enqueue(curr);


            } while (s0 < 4_000_000);
            

            return total;
        }

        public override void Run()
        {
            var total1 = GetSumAproach1();
            var total = GetSumAproach2();

            Console.WriteLine(total1);
            Console.WriteLine(total);
        }
    }
}
